# Site
title: 英语
subtitle: '考研英语'
description: '考研,英语'
keywords: '考研,英语,完型,阅读'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://github.com/daxia000/daxia000
root: /yingyu
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source_yingyu
public_dir: public/yingyu
tag_dir: tags/yingyu
archive_dir: archives/yingyu
category_dir: categories/yingyu
code_dir: downloads/code # Include code 文件夹，source_dir 下的子目录
i18n_dir: :lang/yingyu
skip_render: 
  - pdfjs/**
  - yingyu/**